version: '3.1'

services:

  web:
    image: nginx
    depends_on:
      - php
    ports:
      - 8099:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - app:/app
    restart: always 
    
  php:
    build: .
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DB_HOST: db
      DB_DATABASE: docker
      DB_USERNAME: docker
      DB_PASSWORD: docker
    expose:
      - 9000
    volumes:
      - app:/app
    restart: always

  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_ROOT_PASSWORD: docker

volumes:
  app:
  db:

